spring:
 profiles
   active: 
   - dev
---
spring:
 profiles: dev # 开发环境
  application:
   name: springcloud-config-njupt-dev
---
spring:
 profiles: test # 测试环境
  application:
    name: springcloud-config-njupt-test
# 请保存为UTF-8模式
